# Generated by Django 2.0.2 on 2018-06-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180601_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
