# Generated by Django 2.0.2 on 2018-06-01 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180601_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
