# Generated by Django 2.0.2 on 2018-06-01 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180601_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=199, primary_key=True, serialize=False),
        ),
    ]
