# Generated by Django 2.0.2 on 2018-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180601_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_url',
            field=models.CharField(blank=True, max_length=199, null=True, verbose_name='短连接'),
        ),
    ]
