# Generated by Django 2.0.2 on 2018-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_course_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='modify_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='修改次数'),
        ),
    ]
