# Generated by Django 2.0.2 on 2018-06-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_card_modify_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='modify_count',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='修改次数'),
        ),
    ]
